### ISSUE TITLE
Creating pages is a pain

### ISSUE THREAD

**Issue by keetron** [fhoeben/sample-fitnesse-project#1]
The installation is working well in the current version, using IntelliJ I get a perfectly running wiki.

The problem is: without any real knowledge on how FitNesse works, this is a pain to use. If I modify the FrontPage and build a little default project containing the possible files with some quick explanations, and put it in git and create a PR for you, will it be included and not overwritten by new `clean compile exec:exec` builds?

**Comment by fhoeben** [comment]
Of course. Getting started with FitNesse is not as easy as it could be, some pointers/samples can help a lot. But let's see whether we can keep a good balance between the HsacExamples and these new pages: having stuff in two places will make it harder to maintain and maybe also harder to understand/use for people. I suppose there needs to be a clear distinction between the two, and some cross referencing. But I look forward to your suggestions.

I actually would prefer it if you add the pages to https://github.com/fhoeben/fitnesse-project-archetype, which I use to generate this sample. Or do you think it would be better to only have the extra pages here?

**Comment by keetron** [comment]
What I am now discovering, after working only on already existing projects, is how bare-bones the out of the box version of FitNesse actually is and how that translates to this project.

So to improve the world, while building from scratch to improve my own knowledge, I will build this template project with SuiteSetup and whatnot in whatever place you think is best. As I am not familiar with archetypes (just not sure what it is), I figured the FitNesse Sample project would be the best place for a sample project.

**Comment by fhoeben** [comment]
An archetype is a Maven thing to generate projects. Basically it replaces download and edit from a sample with creating from an archetype which will ask for some input parameters, and then place files with the parameters applied in appropriate places in a new project. (See the latest [README](https://github.com/fhoeben/hsac-fitnesse-fixtures#to-create-your-own-test-project) in hsac-fitnesse-features to see how archetype can be used vs usage of sample project)

If you update the sample project I can copy the wiki pages you build to the archetype, to have them included in any project it generates. By putting it in the archetype we could even ask the user for a suite name (a new input parameter to the archetype) and then have your new content be placed at the appropriate place in the wiki.

But then we might actually need two archetypes: one to set up an installation that does only service/backend tests (no Selenium configuration required), and one that also does browser based tests (which also needs a Selenium setup in its suite setup).

**Comment by fhoeben** [comment]
I've added an empty sample suite containing a child suite for both front- and backend tests to the archetype (https://github.com/fhoeben/fitnesse-project-archetype/releases/tag/1.0.13), and this sample project. I expect this will help alleviate this issue.
