### ISSUE TITLE
Parameter problem.

### ISSUE THREAD

**Issue by blling** [fhoeben/sample-fitnesse-project#6]
These parameters not defined, what are the used for ?
```maven
<systemPropertyVariables>
    <fitnesseSuiteToRun>${fitnesseSuiteToRun}</fitnesseSuiteToRun>
    <seleniumDefaultTimeout>${seleniumDefaultTimeout}</seleniumDefaultTimeout>
     <seleniumGridUrl>${seleniumGridUrl}</seleniumGridUrl>
    <seleniumBrowser>${seleniumBrowser}</seleniumBrowser>
    <seleniumDriverClass>${seleniumDriverClass}</seleniumDriverClass>
    <seleniumCapabilities>${seleniumCapabilities}</seleniumCapabilities>
    <seleniumJsonCapabilities>${seleniumJsonCapabilities}</seleniumJsonCapabilities>
</systemPropertyVariables>
```

**Comment by fhoeben** [comment]
They are present so a run in a build server can change the suite to be run, and the selenium configuration used without any changes in the code base.
See https://github.com/fhoeben/hsac-fitnesse-fixtures/wiki#2-run-on-build-server and https://github.com/fhoeben/hsac-fitnesse-fixtures/wiki/3.1.-Build-Server-Selenium-Configuration

**Comment by blling** [comment]
Get it, thanks !
