### ISSUE TITLE
Question - FitNesse - Reporting

### ISSUE THREAD

**Issue by Blackpander** [fhoeben/sample-fitnesse-project#7]
Hi Fried,

I have a question about reporting with you sample project. I use the standalone in a VSTS pipeline with the FitNesse Command Line Option and want to get results. I'm not allowed to use maven, so my question is: Can I get a fitnesse-results folder with a html report without any extra tools?

Thank you!

**Comment by fhoeben** [comment]
How exactly do you run your tests (what exactly do you mean by 'FitNesse Command Line Option', which command do you have VSTS execute)?

I only have experience running in build servers via the jUnit test. Which I know can be done easily via Maven, Gradle or Ant. Are you not able/allowed to use any such tools? I thought VSTS had Maven support by default these days (https://docs.microsoft.com/en-us/vsts/build-release/tasks/build/maven)?

**Comment by Blackpander** [comment]
The goal is creating a test pipeline were the latest Fitnesse with HSAC is cloned from our git server in to an Azure VM with container, then the wiki pages to use in the test are cloned from another git repository connected to any team their Fitnesse-server(every team has their own repository with scripts). Then the test will run with a script in this pipeline like this:

java -jar fitnesse-standalone.jar -c "MyTestPage?test&format=text"

After that we would like to have a folder with a html-report so we can import this as an artifact and clean up the container. We are for now not allowed to use Maven or Jenkins and only have Fitnesse with HSAC, Azure and VSTS. We already have everything working with Jenkins, Docker and Maven but are now trying to get this within VSTS.

The only problem is the report generating which i'm stuck at. Thanks for you help!

**Comment by fhoeben** [comment]
I have no experience using this way to start fitnesse, but to me the format parameter suggests other values are allowed. Could you use for instance `format=html` instead of the text version?

I don't believe this will generate a nice single folder also containing everything in the 'files section' of the wiki. I suspect it will generate HTML files in a directory and you have to make sure you gather the generated files yourself and keep them (at correct relative path) with the generated HTMLs as artefact.

Another approach might be to use jUnit's console runner to run the tests (similar to what maven would do). That would create the same folder as running via Maven. But I don't know whether that is an option.

**Comment by fhoeben** [comment]
Did you find an approach that works for you?

**Comment by Blackpander** [comment]
Hi @fhoeben, sorry for my late reply. I ended up installing Maven and running it with that. I'm still looking for the best way for this but it works, Thank you!

**Comment by fhoeben** [comment]
@Blackpander I've recently (in the 3.22.0 release) added [a Java class](https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/master/src/main/java/nl/hsac/fitnesse/junit/JUnitConsoleRunner.java) that you can use to run tests without the need for Maven (or Java build tools like it), if you already have a jUnit test class compiled using the `FitNesseRunner` to start the suite.

I've used this to create docker images ([with](https://hub.docker.com/r/hsac/fitnesse-fixtures-test-jre8-chrome/) and [without browser](https://hub.docker.com/r/hsac/fitnesse-fixtures-test-jre8/)) that you can use to run tests based on your wiki content without the need to compile any Java code inside a docker container (if you don't need custom fixtures, if you do need those you still need to compile those and add them to your container, of course). 

I thought this might be use in your pipelines where you wanted to run without Maven. Let me know!
